"use client"
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Navbar/>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
